# Generated by Django 3.1.5 on 2022-01-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
