# Generated by Django 3.1.5 on 2022-01-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_like_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='postid',
            new_name='likepostid',
        ),
    ]
