# Generated by Django 3.1.5 on 2022-01-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220118_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
